version: "3.9"

services:
  mongodb:
    build:
      context: ./documentos
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  neo4j:
    build:
      context: ./grafos
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data
    restart: unless-stopped

volumes:
  mongodb-data:
  neo4j-data:
